//Home
//Fetch stations
export const FETCH_STATIONS_REQUEST = "FETCH_STATIONS_REQUEST";
export const FETCH_STATIONS_SUCCESS = "FETCH_STATIONS_SUCCESS";
export const FETCH_STATIONS_FAIL = "FETCH_STATIONS_FAIL";
export const SEARCH_STATION_REQUEST = "SEARCH_STATION_REQUEST";
export const SEARCH_STATION_SUCCESS = "SEARCH_STATION_SUCCESS";
export const SEARCH_STATION_FAIL = "SEARCH_STATION_FAIL";
//Player
export const PLAY_STATION = "PLAY_STATION";
export const BACK_TO_HOME = "BACK_TO_HOME";
export const CHANGE_STATION = "CHANGE_STAION";

//Favourites
export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const ADD_TO_FAVOURITES_SAVE = "ADD_TO_FAVOURITES_SAVE";
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";
export const FETCH_FAVOURITES = "FETCH_FAVOURITES";
export const FETCH_FAVOURITES_FAIL = "FETCH_FAVOURITES_FAIL";

export const TOGGLE_SELECTION_BAR = "TOGGLE_SELECTION_BAR";

//Settings

export const NIGHT_MODE = "NIGHT_MODE";
export const FETCH_COUNT_CHANGE = "FETCH_COUNT_CHANGE";
export const FETCH_SETTINGS = "FETCH_SETTINGS";
